= Projekt proposal
Elias Just
1.0.0, 2021-010-20: ITP
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// print the toc here (not at the default position)
//toc::[]

==  Sync Moodle to Trello

=== Technologien
=== Projekthintergrund
https://Trello.com[Trello] ist ein umfassendes Tool um Aufgaben zu tracken und zu organisieren. Deshalb ist, wäre ein Tool mit dem man seine Moodle Aufgaben zu Trello automatisch konvergieren kann sehr nützlich.

=== Ziele

==== Zweck
Das Programm dient zur synchronising von Aufgaben, von Moodle zu Trello.

==== Endergebnis
* Der Server soll am Raspberry laufen.
* In einer Datenbank werden die Synchronisierten Daten zwischen gespeichert.
* Bei Bedarf sollen die Application mehrere user verwenden können.
* In einer Grafische Benutzeroberfläche kann man den Serverstatus auslesen und sich ansehen wie lang man durchschnittlich für eine Aufgabe benötigt.( beliebig erweiterbar)

==== Kriterien
* Aufgaben werden zu Trello automatisch synchronisiert
* Es wird mit der Datenbank überprüft, ob die Aufgaben bereits in Trello hochgeladen wurden.
* Es wird überprüft, ob sich Daten in Moodle geändert haben.





